<!-- BEGIN_TF_DOCS -->
cidr_block              = ""
enable_dns_hostnames    = false
enable_dns_support      = true
enable_internet_gateway = false
enable_nat_gateway      = false
name                    = ""
subnets                 = {}
tags                    = {}
<!-- END_TF_DOCS -->